packages:
  - 'admin'
  - 'storefront'
  - 'packages/ui'
overrides:
  '@orkoruta/shared': 'link:../packages-ruta/shared'
  '@orkoruta/db': 'link:../packages-ruta/db'
allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@orkoruta/shared'
  - '@orkoruta/db'
