services:
  - type: web
    name: ruta-admin
    runtime: static
    repo: https://github.com/orkoruta/frontend-ruta
    rootDir: .
    buildCommand: >-
      npm install pnpm@11.3.0 --no-save &&
      node_modules/.bin/pnpm install --frozen-lockfile &&
      node_modules/.bin/pnpm --filter @ruta/admin build
    staticPublishPath: ./admin/out
    envVars:
      - key: NPM_TOKEN
        sync: false
      - key: NEXT_PUBLIC_API_URL
        value: https://ruta-api.onrender.com

  - type: web
    name: ruta-storefront
    runtime: static
    repo: https://github.com/orkoruta/frontend-ruta
    rootDir: .
    buildCommand: >-
      npm install pnpm@11.3.0 --no-save &&
      node_modules/.bin/pnpm install --frozen-lockfile &&
      node_modules/.bin/pnpm --filter @ruta/storefront build
    staticPublishPath: ./storefront/out
    envVars:
      - key: NPM_TOKEN
        sync: false
      - key: NEXT_PUBLIC_API_URL
        value: https://ruta-api.onrender.com
